import { Poppins } from "next/font/google";
// import type { Metadata } from "next";
import "./globals.css";
// import { metadata } from "./metadata";
// import AuthListener from "@/components/authListener";
// import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "600"],
  variable: "--font-poppins",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.variable}`}>
        {/* <Toaster position="bottom-center" /> */}
        {/* <AuthListener /> Read auth changes */}
        <div className="md:hidden">{children}</div>
        <div className="hidden md:block text-center">
          Only Supported in mobile devices
        </div>
      </body>
    </html>
  );
}


